name: contoso-traders-provisioning-deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      [
        "src/ContosoTraders.Api.Carts/**",
        "src/ContosoTraders.Api.Core/**",
        "src/ContosoTraders.Api.Images/**",
        "src/ContosoTraders.Api.Products/**",
        "src/ContosoTraders.Ui.Website/**",
      ]

jobs:
  provision-and-deploy:
    strategy:
      matrix:
        environmentName: [TEST, PROD]
    uses: ./.github/workflows/contoso-traders-provisioning-deployment-template.yml
    secrets: inherit
    with:
      environmentName: ${{ matrix.environmentName }}
