name: contoso-traders-ui-old

on:
  workflow_dispatch:

env:
  STORAGE_ACCOUNT_NAME: contosotradersui
  CDN_PROFILE_NAME: contoso-traders-cdn
  CDN_ENDPOINT_NAME: contoso-traders-ui
  CDN_RESOURCE_GROUP_NAME: contoso-traders-rg

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        ref: old-ui # Branch created from commit bed687acc55374cf9f166ba8d518a046c1791724 (last commit having old ui)
    - name: npm install
      run: npm install
      working-directory: src/ContosoTraders.Ui.Website
    - name: npm run build
      run: npm run build
      working-directory: src/ContosoTraders.Ui.Website
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.SERVICEPRINCIPAL }}
    - name: deploy to storage
      uses: azure/CLI@v1
      with:
        inlineScript: az storage blob sync --account-name '${{ env.STORAGE_ACCOUNT_NAME }}${{ secrets.ENVIRONMENT }}' -c '$web' -s 'src/ContosoTraders.Ui.Website/build'
    - name: purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: az cdn endpoint purge --no-wait --content-paths '/*' -n '${{ env.CDN_ENDPOINT_NAME }}${{ secrets.ENVIRONMENT }}' -g '${{ env.CDN_RESOURCE_GROUP_NAME }}' --profile-name '${{ env.CDN_PROFILE_NAME }}${{ secrets.ENVIRONMENT }}'
